name: swayamsesatyatak
description: "get freedom from self."

publish_to: 'none'



version: 1.0.1+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.4
  email_validator: ^3.0.0
  go_router: ^14.3.0
  cloud_firestore: ^5.4.4
  http: ^0.13.0
  youtube_player_flutter: ^9.1.1
  image_picker: ^1.1.2
  firebase_storage: ^12.3.4
  image: ^4.3.0
  cloudinary: ^1.2.0
  flutter_html: ^3.0.0-beta.2
  flutter_pdfview: ^1.3.4
  flutter_tts: ^4.0.2
  path_provider: ^2.1.5
  open_file: ^3.5.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/swayam_se_satya_tak.png
    - assets/images/walkthrough/walkthrough1.webp
    - assets/images/walkthrough/walkthrough2.webp
    - assets/images/walkthrough/walkthrough3.webp

